---
- name: OpenOnDemand | include EL8 Slurm vars
  include_vars: /opt/oci-hpc/playbooks/roles/slurm/vars/el_vars.yml
  when:
    - use_ood | default(false) | bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'
    - ansible_distribution_major_version | string == '8'

- name: OpenOnDemand | include EL8 tasks (Oracle Linux 8)
  include_tasks: el8.yml
  when:
    - use_ood | default(false) | bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'
    - ansible_distribution_major_version | string == '8'

- name: OpenOnDemand | include Ubuntu Slurm vars
  include_vars: /opt/oci-hpc/playbooks/roles/slurm/vars/ubuntu_vars.yml
  when:
    - use_ood | default(false) | bool
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('24.04', '==')

- name: OpenOnDemand | include Ubuntu 24.04 tasks
  include_tasks: ubuntu24.yml
  when:
    - use_ood | default(false) | bool
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('24.04', '==')
