---
ood_dcv_enabled: false
ood_desktop_use_gpu: false
ood_dcv_queue: dcv
ood_dcv_expected_gpu: NVIDIA A10

ood_dcv_version: "2025.0-20103"
ood_dcv_archive_name: "nice-dcv-{{ ood_dcv_version }}-el8-x86_64.tgz"
ood_dcv_archive_url: >-
  https://d1uj6qtbmh3dt5.cloudfront.net/2025.0/Servers/{{ ood_dcv_archive_name }}
ood_dcv_archive_sha256: a3038cb0119c9e287c08afb84c687e48896cb4e7af2f9c8a7724b5ae9226e718
ood_dcv_gpg_key_url: https://d1uj6qtbmh3dt5.cloudfront.net/NICE-GPG-KEY
ood_dcv_gpg_key_sha256: d772e9783689d014810ccd8f014169bdf1db37ebcf686c92f8423e44c6f81912

ood_dcv_cache_dir: /var/cache/ood-dcv
ood_dcv_archive_path: "{{ ood_dcv_cache_dir }}/{{ ood_dcv_archive_name }}"
ood_dcv_extract_dir: "{{ ood_dcv_cache_dir }}/nice-dcv-{{ ood_dcv_version }}-el8-x86_64"
ood_dcv_gpg_key_path: "{{ ood_dcv_cache_dir }}/NICE-GPG-KEY"
ood_dcv_vgl_group: "{{ ood_vnc_vgl_group | default('vglusers') }}"

ood_dcv_common_rpms:
  - name: nice-dcv-server-2025.0.20103-1.el8.x86_64.rpm
    sha256: 7fee5b826a1326b3541960e489ed9f0bb028ca54cc5bd63b1617e920f7931cf8
    verify_path: /usr/lib/systemd/system/dcvserver.service
  - name: nice-dcv-web-viewer-2025.0.20103-1.el8.x86_64.rpm
    sha256: 297f343a1b2957731bb35a9a141604f83abd02b2d11ddec6d2e336b1a811a585
    verify_path: /usr/share/dcv/www/index.html
  - name: nice-xdcv-2025.0.688-1.el8.x86_64.rpm
    sha256: bade2233d79217c2868f0117c48c88a106e1b12d0e7cd63843f8b1a48cae5fd4
    verify_path: /usr/bin/Xdcv
  - name: nice-dcv-simple-external-authenticator-2025.0.282-1.el8.x86_64.rpm
    sha256: 232a7ac59c19573ce31f6b4c323ed2c30352b0c424f73e442e71cf159daebfad
    verify_path: /usr/lib/systemd/system/dcvsimpleextauth.service

ood_dcv_gpu_rpms:
  - name: nice-dcv-gl-2025.0.1112-1.el8.x86_64.rpm
    sha256: 80bfed40233a06aac0cb4b99ccfcfeff800c71c62ad6a39a2bd70896c38fed3b
    verify_path: /usr/sbin/dcvgladmin
